force-app/main/default/objects/WhatsApp_Template__c/WhatsApp_Template__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Template</label>
    <nameField>
        <label>WhatsApp Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WhatsApp Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsApp_Template__c/fields/language__c.field-meta.xml
<CustomField>
    <fullName>language__c</fullName>
    <label>language</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Template__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <description>Used for storing the template name</description>
    <label>Template Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TemplateWithProducts.cls
public class TemplateWithProducts {
    public static void sendTemplateForProducts() {
        String whatsAppNumber = '919688490676';
        List<WhatsApp_Template__c> templates = [SELECT Id, Template_Name__c, language__c 
            FROM WhatsApp_Template__c WHERE Template_Name__c = 'three_products' LIMIT 1];
        String temp = templates[0].Template_Name__c;
        String lang = templates[0].language__c;
        List<String> data = new List<String>();
 
        WhatsAppTemplateController.sendTemplateMessage(whatsAppNumber, temp, lang, data);
    }
    // WhatsAppTemplateController.sendTemplateMessageForRequest(whatsappNumber, temp, lang, data);
}