force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <!---->
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <label>Message Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Receiver__c.field-meta.xml
<CustomField>
    <fullName>Receiver__c</fullName>
    <label>Receiver</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <label>Sender</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchPdfGen.cls
public class BatchPdfGen implements Database.Batchable<SObject> {
    private Id recordIds;

    public BatchPdfGen(Id recordId) {
        this.recordIds = recordId;
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([
            SELECT Id, Sender__c, Receiver__c, Status__c, Message_Body__c
            FROM Message__c
            WHERE Id =:recordIds
        ]);
    }

    public void execute(Database.BatchableContext context, List<Message__c> scope) {

        for (Message__c record : scope) {
            try {
                PageReference pdfPage = Page.Generatepdf;
                pdfPage.getParameters().put('id', record.Id);

                Blob pdfBlob = pdfPage.getContentAsPDF();
                system.debug('pdfblob');

                ContentVersion contentVersion = new ContentVersion();
                system.debug('contentversion');
                contentVersion.Title = 'Message PDF - ' + record.Id;
                System.debug('title');
                contentVersion.PathOnClient = 'MessageDetails.pdf';
                System.debug('path on client');
                contentVersion.VersionData = pdfBlob;
                System.debug('versiondata');
                contentVersion.IsMajorVersion = true;
                System.debug('ismajor version');

                insert contentVersion;
                System.debug('Inserted');
            } catch (Exception e) {
                System.debug('Error generating PDF for record: ' + record.Id + ' - ' + e.getMessage());
            }
        }
    }

    public void finish(Database.BatchableContext context) {
        System.debug('Batch processing completed.');
    }
}